### PR TITLE
Temporary fix for 8.0.0-beta6: Blocking connection/socket when using Chrome

### LINKED ISSUE #31: HTTP Requests from Chrome block the server
There seems to be a problem handling requests from Chrome. Chrome locks the http server for a minute, blocking any other requests from being handled - other than requests from the same Chrome tab. A minute after the last request from Chrome, the server will start handling other requests again.

If you start a server, it will handle requests correctly from clients like node-red, firefox etc. (anything other than Chrome!). 
If you are looping with server.poll() the loop will run correctly, but will freeze for 60 seconds after the Chrome request.
An example from an ESP32-S3 I am using:

```
pool = socketpool.SocketPool(wifi.radio)
server = HTTPServer(pool)
server.request_buffer_size = 2048
server.socket_timeout = 1
server.start(str(wifi.radio.ipv4_address))

@server.route("/")
def base(request: HTTPRequest):
    with HTTPResponse(request, content_type=MIMEType.TYPE_TXT, chunked=False) as response:
        try:
            print("REQUEST: /")
            response.send("HELLO")
        except OSError:
            response.send("ERROR")

while True:
    try:
        led.value = True
        time.sleep(0.05)
        led.value = False
        time.sleep(0.1)
        server.poll()
        
    except OSError as error:
        print(error)
        continue
```

As soon as you hit the server with Chrome, the server responds but stops the loop and stops handling requests from other clients. If you make another request from chrome in the same tab, it will be handled, and seemingly at that time pending requests from other clients can sometimes be handled but the loop will freeze again right after.

Making a request to an undefined path from Chrome freezes the loop also - you get the 404 in chrome and then server loop freezes - whatever code you put in your handler does not fix this problem.

A minute after the last Chrome request, the loop restarts and the server functions normally.

If you quit Chrome while the loop is locked, the loop restarts immediately.

I've tried a bunch of things to fix this, including closing the connection in the handler, sending various keep-alive responses to drop the connection - none work.

I think this needs an SDK level fix!

### PR DESCRIPTION
**Pull request by michalpokusa**
Experimental change in `HTTPServer.poll()` that fixes blocked connection from Chrome on CircuitPython 8.0.0

Fixes #31 

**EDIT 1: This is a workaround fix that should be used only on 8.0.0-beta6. When 8.0.0-beta7 or 8.0.0 is released this PR should be closed.**

### CODE REVIEW

**Comment by michalpokusa** [comment]
Unfortunately this does not work in CircuitPython 7.3.3, `pooler.pool()` raises `OSError: stream operation not supported`.

Although it can be written in a way that the pooler runs only on CP 8.x.x with a simple if statement, I don't really believe it is a way to go.

Additionally even in `select` [library docs](https://docs.circuitpython.org/en/latest/docs/library/select.html) it says that this functionality is not supported on all CP builds.
image

Right now, this lib is not working properly on CP 8.0.0beta6, so wraping this code in `try...except...` might be a good temporary solution, until the underlaying error in CP's 8.0.0 `socketpool` is resolved.

**Comment by dhalbert** [comment]
I think the underlying problem that makes this fix needed is fixed by https://github.com/adafruit/circuitpython/pull/7455. @michalpokusa Do you think this is useful anyway, or is it only needed as a workaround?

**Comment by michalpokusa** [comment]
> I think the underlying problem that makes this fix needed is fixed by [adafruit/circuitpython#7455](https://github.com/adafruit/circuitpython/pull/7455). @michalpokusa Do you think this is useful anyway, or is it only needed as a workaround?

Seems that PR to CP indeed fixes the blocking socket issue.

This PR was an experimental workaround to make this lib work on 8.0.0-beta6, but it had some issues connected to `select` module on 7.3.3.

In my opinion it is somewhat useful **until your changes are merged and released under e.g. 8.0.0-beta7** as some people might still have problem and this PR might help them solve it.
After that it should be closed as no longer needed.

**Comment by FoamyGuy** [comment]
`8.0.0-rc.1` and now `8.0.0` stable have been released so this can be close now I think.

**Pull request closed without merging**
