### PR TITLE
Auto-serve `index.html` for root path

### PR DESCRIPTION
**Pull request by matemaciek**

### CODE REVIEW

**Comment by michalpokusa** [comment]
This implementation defaults to `index.html` only for root path. For e.g. `192.168.x.x/other-location/` still behaves the same way as current stable version.

One possible solution would be checking if the provided location is a folder, and if yes, then defaulting to `index.html`.

It is also important to explain this behavoiur in docs.

**Comment by matemaciek** [comment]
Maybe we want apache-style directory listing if there's no `index.html`? Since we're already serving all files by default.

**Comment by michalpokusa** [comment]
Personally, if we were talking about a Python lib, I would agree, but this one is for microcontrollers, often ones that do not have much storage and memory.  Keeping that in mind, in my opinion, this lib should only provide enough functionality to easily spin up a HTTP server, without doing anything else.

Nevertheless, it is up to the maintainers to decide.

**Review by FoamyGuy — APPROVED** [review]
This looks good to me. I tested successfully with a slightly modified simpletest on a feather TFT esp32s2.

I think it is probably best not to have the default behavior of file listing inside the library since it is intended for use in relatively minimal micro-controller environments. 

However I do also think it could make a good example script if someone wanted to implement the functionality and share it for folks who might be interested in it. 

Thank you @matemaciek

**Pull request merged**
